### PR TITLE
Add link to Doku

### PR DESCRIPTION
**Pull request by DevTown**
I have add a link to the Doku in top of the Page. Issue #104 gave me the Hint.

### CODE REVIEW

**Comment by matham** [comment]
What is "doku"?

**Comment by DevTown** [comment]
Documentation. ;-) Got a wrong short form sorry.

**Comment by tshirtman** [comment]
i agree it should be there, not sure why it was removed, but if there is a good reason i'd rather see it fixed than removed, we want users to read the documentation more, not less.

**Comment by matham** [comment]
This broke the links it seems as none of the links are being displayed on the front page anymore.

**Comment by janek37** [comment]
Is that it? The link is no longer needed?

**Comment by DevTown** [comment]
I Think it is needed.  I will have a look if I can bring it into without breaking the page.

**Pull request merged**
