### PR TITLE
remove references to the kivy VM

### PR DESCRIPTION
**Pull request by tshirtman**
until we provide an alternative

### CODE REVIEW

**Comment by Zen-CODE** [comment]
What's the background for this? Are there too many issues with people using the an outdated VM?

**Comment by tshirtman** [comment]
Well, they can download it, and then not only the installed tools are broken for being too old, but installing anything is impossible since the repositories for this version of ubuntu have been decommissioned. So i don't know how many people it happens to, but i don't think this particular image can help anybody anymore.

I'd be fine with replacing it with something newer and better, if you want to put yours instead.

**Comment by Zen-CODE** [comment]
Agreed. I see work as also been done on containers that can build, so I'll do some research and submit a new PR for the options available.

**Comment by Zen-CODE** [comment]
I assume we can delete the branch?

**Pull request merged**
